---

- tags:
    - yum
    - packages
  block:

    #------------------------------------------------------------------------------#
    # install nginx
    #------------------------------------------------------------------------------#

    - name: install nginx
      yum:
        name: nginx
        state: present
